name: Node.js CI

on:
  pull_request:
  push:
    branches: ["main", "develop", "feature/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 24
        uses: actions/setup-node@v2
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
